#
# To create database
#       docker-compose run web rake db:setup
#
# Execute command to start mysql and rails:
#       docker-compose up
#
version: '3.5'

services:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rtb4free
      - MYSQL_DATABASE=rtb4free
      - MYSQL_USER=rtb4free
      - MYSQL_PASSWORD=rtb4free
    networks:
      - r4f_net

  web:
    image: rtb4free/campaign-manager
    ports:
      - "3000:3000"
    environment:
      - CUSTOMER_NAME=RTB4FREE
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=rtb4free
      - DB_PASSWORD=rtb4free
      - DB_NAME=rtb4free
      - ELASTICSEARCH_ENABLE=false
      - ELASTICSEARCH_HOST=
      - ELASTICSEARCH_KIBANA_URL=
    depends_on:
      - db
    networks:
      - r4f_net
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

volumes:
  db_data: {}

networks:
  r4f_net:
    name: rtb4free_network
