class Exchange < ActiveRecord::Base
    
    
    def self.all
        [
            { name:"atomx"},
            { name:"cappture"},
            { name:"epomx"},
            { name:"fyber"},
            { name:"gotham"},
            { name:"nexage"},
            { name:"smartyads"},
            { name:"smaato"},
            { name: "kadam"}, 
            { name: "citenko"},
            { name: "taggify"},
            { name: "ssphwy"},
            { name: "admedia"},
            { name: "republer"},
            { name: "pubmatic"},
            { name: "adventurefeeds"},
            { name: "axonix"},
            { name: "intango"},
            { name: "medianexusnetwork"},
            { name: "smartadserver"},
            { name: "waardx"},
            { name: "wideorbit"},
            { name: "c1x", label:"C1X"},
            { name: "appnexus",
                attributes: [
                    {
                        name: "appnexus_crid",
                        label: "Appnexus Creative ID",
                        value: "",
                        form_type: "input"
                    }
                ]
            },
            { name: "adx",
                label: "AdX",
                attributes: [
                    {
                        name: "click_thru_url",
                        label: "Click Through URL",
                        value: "",
                        form_type: "input"
                    },    
                    {
                        name: "tracking_url",
                        label: "Tracking URL",
                        value:  "",
                        form_type: "input"
                    },
                    {
                        name: "categories",
                        label: "Categories",
                        value: "",
                        form_type: "select_multi",
                        select_options: [
            				{ value: '0', label: 'Ad has no restricted categories'},
            				{ value: '3', label: 'Politics'},
            				{ value: '4', label: 'Dating'},
            				{ value: '5', label: 'Religon'},
            				{ value: '7', label: 'Video Games (Casual, Online)'},
            				{ value: '8', label: 'Ringtones and Downloadables'},
            				{ value: '10', label: 'Get Rich Quick'},
            				{ value: '18', label: 'Weight Loss'},
            				{ value: '19', label: 'Cosmetic Procedures & Body Modification'},
            				{ value: '23', label: 'Drugs & Supplements'},
            				{ value: '24', label: 'Sexual and Reporoductive Health'},
            				{ value: '28', label: 'Free Gifts, Quizzes & Surveys'},
            				{ value: '29', label: 'Misleading CLaims.'},
            				{ value: '30', label: 'Black Magic, Astrology , Occult'},
            				{ value: '31', label: 'References to Sex and Sexuality'},
            				{ value: '33', label: 'Alcohol'},
            				{ value: '12950', label: '401(K)s'},
            				{ value: '12849', label: 'Air Cleaners & Filters'},
            				{ value: '13606', label: 'American Football'},
            				{ value: '13314', label: 'Anti-Virus Software'},
            				{ value: '13530', label: 'Arts & Entertainment Awards'},
            				{ value: '13469', label: 'Astrology & Horoscopes'},
            				{ value: '13686', label: 'Attorneys & Law Firms'},
            				{ value: '13801', label: 'Audio Books'},
            				{ value: '12957', label: 'Auto Financing'},
            				{ value: '13284', label: 'Auto Leasing'},
            				{ value: '13610', label: 'Baseball'},
            				{ value: '13609', label: 'Basketball'},
            				{ value: '13657', label: 'Boat & Yacht Sales & Brokers'},
            				{ value: '13422', label: 'Body Art'},
            				{ value: '13474', label: 'Buddhism'},
            				{ value: '13797', label: 'Building Materials & Supplies'},
            				{ value: '12209', label: 'Business & Productivity Software'},
            				{ value: '13292', label: 'Buy-To-Let Mortgages'},
            				{ value: '12766', label: 'Cable TV'},
            				{ value: '13656', label: 'Car Dealers'},
            				{ value: '13760', label: 'Cartoons'},
            				{ value: '13491', label: 'Chemical Industry'},
            				{ value: '13780', label: 'Children\'s Clothing'},
            				{ value: '13472', label: 'Christianity'},
            				{ value: '13722', label: 'Cleansing & Detoxification'},
            				{ value: '13633', label: 'Combat Sports'},
            				{ value: '12956', label: 'Commercial Lending'},
            				{ value: '13283', label: 'Commercial Mortgages'},
            				{ value: '13377', label: 'Computer & Video Games'},
            				{ value: '12867', label: 'Contact Lenses & Accessories'},
            				{ value: '13768', label: 'Domain Names & Domain Name Registration'},
            				{ value: '13567', label: 'Edgy & Bizarre'},
            				{ value: '13094', label: 'Email & Messaging'},
            				{ value: '12866', label: 'Eyeglass Frames'},
            				{ value: '13536', label: 'Film & TV Industry'},
            				{ value: '13293', label: 'Fixed Rate Mortgages'},
            				{ value: '13489', label: 'Fun Tests & Silly Surveys'},
            				{ value: '13425', label: 'Fun & Trivia'},
            				{ value: '13658', label: 'Gardening'},
            				{ value: '12777', label: 'Garden Structures'},
            				{ value: '13369', label: 'Gene Research'},
            				{ value: '13291', label: 'Government Mortgages'},
            				{ value: '13513', label: 'Graduate Programs'},
            				{ value: '13423', label: 'Guns & Firearms'},
            				{ value: '13740', label: 'Halloween & October 31st'},
            				{ value: '12263', label: 'Handbags & Purses'},
            				{ value: '13475', label: 'Hinduism'},
            				{ value: '13611', label: 'Hockey'},
            				{ value: '13509', label: 'Holidays & Seasonal Events'},
            				{ value: '13296', label: 'Home Equity Loans & Lines of Credit'},
            				{ value: '12960', label: 'Home Loans & Mortgages'},
            				{ value: '13299', label: 'Home Refinancing Loans'},
            				{ value: '13525', label: 'Horror Films'},
            				{ value: '13612', label: 'Hunting & Shooting'},
            				{ value: '13464', label: 'Industrial Goods & Manufacturing'},
            				{ value: '13289', label: 'Interest Only Mortgages'},
            				{ value: '13418', label: 'Internet'},
            				{ value: '12204', label: 'Internet Software & Web Goodies'},
            				{ value: '12952', label: 'IRAs'},
            				{ value: '13473', label: 'Islam'},
            				{ value: '13116', label: 'Jerseys & Knit Shirts'},
            				{ value: '13476', label: 'Judaism'},
            				{ value: '12187', label: 'Laptop Computers'},
            				{ value: '12828', label: 'Laundry Detergents'},
            				{ value: '12997', label: 'Massive Multiplayer Online Games'},
            				{ value: '13260', label: 'Mattresses'},
            				{ value: '12494', label: 'Medical Diagnostic Equipment & Monitoring Devices'},
            				{ value: '13778', label: 'Men\'s Clothing'},
            				{ value: '13381', label: 'Mobile Phones & Accessories'},
            				{ value: '13417', label: 'Movies & Films'},
            				{ value: '13428', label: 'Multi-tools & Pocket Knives'},
            				{ value: '12926', label: 'Multi-Vitamins'},
            				{ value: '13092', label: 'Network Security Software'},
            				{ value: '13647', label: 'Newspapers'},
            				{ value: '13439', label: 'Nightclubs, Bars & Music Clubs'},
            				{ value: '13566', label: 'Offbeat'},
            				{ value: '13300', label: 'Payday & Emergency Loans'},
            				{ value: '13710', label: 'People Search'},
            				{ value: '12961', label: 'Personal Lending & Borrowing'},
            				{ value: '13301', label: 'Personal Loans & Lines of Credit'},
            				{ value: '13250', label: 'Pest & Weed Control'},
            				{ value: '13419', label: 'Phone Plans'},
            				{ value: '13596', label: 'Photographic & Digital Arts'},
            				{ value: '12228', label: 'Pizzerias & Pizza Delivery'},
            				{ value: '12590', label: 'Power Tools'},
            				{ value: '13405', label: 'Prizes & Competitions'},
            				{ value: '13470', label: 'Psychics & Fortune Telling'},
            				{ value: '13716', label: 'Public Records'},
            				{ value: '12767', label: 'Satellite TV'},
            				{ value: '13479', label: 'Scientology'},
            				{ value: '12240', label: 'Shirts, Tops & Blouses'},
            				{ value: '13589', label: 'Shooter Games'},
            				{ value: '13608', label: 'Soccer'},
            				{ value: '13493', label: 'Special Occasions'},
            				{ value: '13605', label: 'Sports'},
            				{ value: '13459', label: 'Stocks'},
            				{ value: '12261', label: 'Sunglasses'},
            				{ value: '13680', label: 'Sweepstakes, Product Promotions & Giveaways'},
            				{ value: '12387', label: 'Tax Preparation & Planning'},
            				{ value: '13496', label: 'Theme Parks'},
            				{ value: '13286', label: 'Title Loans'},
            				{ value: '13432', label: 'Translation'},
            				{ value: '13374', label: 'Trees, Plants & Shrubs'},
            				{ value: '13714', label: 'Used Motor Vehicles'},
            				{ value: '12797', label: 'Vacuum Cleaners & Accessories'},
            				{ value: '13655', label: 'Vehicle Dealers'},
            				{ value: '13376', label: 'Video Game Consoles'},
            				{ value: '13388', label: 'Visual Art & Design'},
            				{ value: '12795', label: 'Washers & Dryers'},
            				{ value: '13426', label: 'Weather'},
            				{ value: '13725', label: 'Web Portals'},
            				{ value: '12864', label: 'Weight Loss Drugs & Medications'},
            				{ value: '12865', label: 'Weight Loss Supplements'},
            				{ value: '13620', label: 'Winter Sports'},
            				{ value: '13779', label: 'Women\'s Clothing'}
                        ]
                    },                    {
                        name: "vendor_type",
                        label: "Vendor Type",
                        value: "",
                        form_type: "select",
                        select_options: [
                			{ value: '', label: 'None specified'},
                			{ value: '10', label: 'Tumri'},
                			{ value: '42', label: 'BlueKai'},
                			{ value: '43', label: 'BrightRoll'},
                			{ value: '56', label: 'Efficient Frontier'},
                			{ value: '94', label: 'Nielsen OBE (Vizu) - Survey'},
                			{ value: '130', label: 'Broadband Enterprises'},
                			{ value: '132', label: 'Adlens'},
                			{ value: '144', label: 'Campaign Monitor (Integral Ad Science)'},
                			{ value: '145', label: 'DoubleVerify'},
                			{ value: '182', label: 'comScore - vCE'},
                			{ value: '204', label: 'Pulpo Media'},
                			{ value: '225', label: 'Zanox'},
                			{ value: '226', label: 'DoubleClick Rich Media Expandable'},
                			{ value: '228', label: 'Sizmek Expandable'},
                			{ value: '229', label: 'PointRoll Expandable'},
                			{ value: '233', label: 'Media Innovation Group (Xaxis)'},
                			{ value: '237', label: 'Reddion'},
                			{ value: '238', label: 'Aggregate Knowledge'},
                			{ value: '242', label: 'Lotame'},
                			{ value: '255', label: 'Accuen'},
                			{ value: '260', label: 'Alenty'},
                			{ value: '267', label: 'DataLogix'},
                			{ value: '284', label: 'Research Now'},
                			{ value: '303', label: 'Millward Brown Digital - Survey'},
                			{ value: '316', label: 'Flashtalking Expandable'},
                			{ value: '331', label: 'Avail Intelligence'},
                			{ value: '332', label: 'Audience Manager(DemDex)'},
                			{ value: '334', label: 'Adloox'},
                			{ value: '342', label: 'Adledge'},
                			{ value: '395', label: 'Adnologies'},
                			{ value: '414', label: 'Batch Media'},
                			{ value: '428', label: 'Conversant (Mediaplex) Expandable'},
                			{ value: '432', label: 'Hi-Media'},
                			{ value: '441', label: 'Hubrus'},
                			{ value: '445', label: 'Project SunBlock'},
                			{ value: '472', label: 'Neustar AdAdvisor'},
                			{ value: '474', label: 'Integral Ad Science Firewall - Ad Swapping'},
                			{ value: '476', label: 'comScore vCE - Ad Swapping'},
                			{ value: '477', label: 'DoubleVerify BrandShield - Ad Swapping'},
                			{ value: '481', label: 'eXelate'},
                			{ value: '485', label: 'comScore - VoiceFive'},							
                			{ value: '486', label: 'AdLoox - Ad Swapping'},
                			{ value: '489', label: 'Revenue Cloud'},
                			{ value: '490', label: 'AdLedge - Ad Blocking'},
                			{ value: '497', label: 'Exactag'},
                			{ value: '520', label: 'Flite - Expandable'},
                			{ value: '523', label: 'Spongecell - Expandable'},
                			{ value: '529', label: 'Eyeliota'},
                			{ value: '537', label: 'Public Eye'},
                			{ value: '538', label: 'Weborama Expandable'},
                			{ value: '539', label: 'Adform - Expandable'},
                			{ value: '542', label: 'Bizo'},
                			{ value: '543', label: 'VisualDNA'},
                			{ value: '549', label: 'Predicta - Expandable'},
                			{ value: '550', label: 'AdYapper'},
                			{ value: '551', label: 'Nielsen Digital Ad Ratings (formerly OCR)'},
                			{ value: '553', label: 'Kpsule - Expandable'},
                			{ value: '554', label: 'Linkstorm - Expandable'},
                			{ value: '562', label: 'Experian'},
                			{ value: '564', label: 'Noddington Technologies Limited (Aidata)'},
                			{ value: '568', label: 'Admotion - Expandable'},
                			{ value: '569', label: 'Contobox Expandable'},
                			{ value: '572', label: 'Webtrekk'},
                			{ value: '573', label: 'Fabric Worldwide'},
                			{ value: '574', label: 'Liveramp'},
                			{ value: '575', label: 'Krux'},
                			{ value: '577', label: 'Ru Target LLC'},
                			{ value: '606', label: 'Gruvi TV'},
                			{ value: '608', label: 'Rockabox Media - Expandable'},
                			{ value: '615', label: 'Nielsen Digital Ad Ratings (formerly OCR) JS'},
                			{ value: '616', label: 'Tealium'},
                			{ value: '617', label: 'Mixpo - Expandable'},
                			{ value: '618', label: 'Demand Side Science'},
                			{ value: '623', label: 'Human Demand'},
                			{ value: '633', label: 'Knorex - Expandable'},
                			{ value: '698', label: 'GET IT Mobile'},
                			{ value: '704', label: 'GlobalWebIndex'},
                			{ value: '713', label: 'MezzoMedia'},
                			{ value: '724', label: 'Extreme Reach ad server'},
                			{ value: '743', label: 'White Ops'},
                			{ value: '745', label: 'adverserve digital advertising services'},
                			{ value: '767', label: 'SFR'},
                			{ value: '776', label: 'Spark Flow'},
                			{ value: '780', label: 'Where 2 Get It'},
                			{ value: '785', label: 'Scrutineer Survey'},
                			{ value: '791', label: 'VideoHub DSP'},
                			{ value: '793', label: 'Semasio'},
                			{ value: '797', label: 'ADmantX'},
                			{ value: '798', label: 'Nielsen Catalina Solutions'},
                			{ value: '806', label: 'Sociomantic Expandable'},
                			{ value: '808', label: 'Hatena'},
                			{ value: '813', label: 'Protected Media'},
                			{ value: '814', label: 'Media Detect'},
                			{ value: '815', label: 'Resonate Networks'},
                			{ value: '818', label: 'Redbranch'},
                			{ value: '820', label: 'iPinyou - Expandable'},
                			{ value: '826', label: 'AmberData'},
                			{ value: '828', label: 'Crutchfield New Media'},
                			{ value: '832', label: 'The ADEX'},
                			{ value: '834', label: 'Jivox - Expandable'},
                			{ value: '838', label: 'Revjet Expandable'},
                			{ value: '863', label: 'Bonzai Expandable'},
                			{ value: '864', label: 'INCUBIQ Solutions'},
                			{ value: '874', label: 'Cint'},
                			{ value: '876', label: 'Exponential Expandable'},
                			{ value: '880', label: 'Navegg'},
                        ]
                    },
                    {
                        name: "attributes",
                        label: "Attributes",
                        value: "",
                        form_type: "select_multi",
                        select_options: [
            				{ value: '21', label: 'Creative type HTML'},
            				{ value: '22', label: 'Creative type VAST Video'},
            				{ value: '7', label: 'Tagging: IsTagged'},
            				{ value: '8', label: 'CookieTargeting: IsCookieTargeted'},
            				{ value: '9', label: 'UserInterestTargeting: IsUserInterestTargeted'},
            				{ value: '12', label: 'ExpandingDirection: ExpandingNone'},
            				{ value: '13', label: 'ExpandingDirection: ExpandingUp'},
            				{ value: '14', label: 'ExpandingDirection: ExpandingDown'},
            				{ value: '15', label: 'ExpandingDirection: ExpandingLeft'},
            				{ value: '16', label: 'ExpandingDirection: ExpandingRight'},
            				{ value: '17', label: 'ExpandingDirection: ExpandingUpLeft'},
            				{ value: '18', label: 'ExpandingDirection: ExpandingUpRight'},
            				{ value: '19', label: 'ExpandingDirection: ExpandingDownLeft'},
            				{ value: '20', label: 'ExpandingDirection: ExpandingDownRight'},
            				{ value: '25', label: 'ExpandingDirection: ExpandingUpOrDown'},
            				{ value: '26', label: 'ExpandingDirection: ExpandingLeftOrRight'},
            				{ value: '27', label: 'ExpandingDirection: ExpandingAnyDiagonal'},
            				{ value: '28', label: 'ExpandingAction: RolloverToExpand'},
            				{ value: '30', label: 'InstreamVastVideoType: Vpaid Flash'},
            				{ value: '32', label: 'MraidType: MRAID'},
            				{ value: '34', label: 'RichMedia capability is Flash'},
            				{ value: '39', label: 'RichMedia capability type is HTML5'},
            				{ value: '47', label: 'RichMedia capability type: RichMediaCapabilitySSL'},
            				{ value: '49', label: 'RichMedia capability type: RichMediaCapabilityNonSSL'},
            				{ value: '70', label: 'NativeEligibility: Native Eligible'},
            				{ value: '72', label: 'NativeEligibility: Native Not Eligible'},
            				{ value: '105', label: 'Rendering: Sizeless AdX'}                            
                        ]
                    }
                ]
            },
            { name: "stroer",
                attributes: [
                    {
                        name: "avn",
                        label: "Advertiser Name",
                        value: "",
                        form_type: "input"
                    },
                    {
                        name: "agn",
                        label: "Agency Name",
                        value: "",
                        form_type: "input"
                    }
                ]
            },
            { name: "adlithium" },
            { name: "vertamedia" },
            { name: "vdopia" },
            { name: "tappx" },
            { name: "spotx" },
            { name: "vmax" },
            { name: "google", 
                attributes: [
                    {
                        name: "billing_id",
                        label: "Billing ID",
                        value: "",
                        form_type: "input"
                    }
                ]
            },
            { name: "pokkt" },
            { name: "pubnative" },
            { name: "ventuno" }
        ].sort_by{|i| i[:name] }
    end
   
    def self.find_exchange(name)
        self.all.find {|s| s[:name].to_s.eql?(name) }
    end
    
end

